# ========== Nombre ==========
spring.application.name=sava

# ========== Informix ==========
informix.datasource.url=${CONNECTION_DB_INFORMIX}
informix.datasource.username=${USERNAME_DB_INFORMIX}
informix.datasource.password=${PASSWORD_DB_INFORMIX}
informix.datasource.driver-class-name=com.informix.jdbc.IfxDriver


# ========== PostgreSQL ==========
postgres.datasource.url=${CONNECTION_DB_POSTGRES}
postgres.datasource.username=${USERNAME_DB_POSTGRES}
postgres.datasource.password=${PASSWORD_DB_POSTGRES}
postgres.datasource.driver-class-name=org.postgresql.Driver